name: grid_lookup
description: "A Flutter package providing a dynamic and flexible grid lookup widget for efficient data selection in forms."
version: 0.0.2

homepage: https://github.com/BoyPhanna/flutter_grid_lookup.git
repository: https://github.com/BoyPhanna/flutter_grid_lookup.git
issue_tracker: https://github.com/BoyPhanna/flutter_grid_lookup.git/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_datagrid: ^27.1.53

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Add assets or fonts if needed
